// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Sparovia.Infrastructure.Data;

#nullable disable

namespace Sparovia.Infrastructure.Migrations
{
    [DbContext(typeof(SparoviaDbContext))]
    [Migration("20261003140000_AddWorkCategoriesAndImageCategory")]
    partial class AddWorkCategoriesAndImageCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
#pragma warning restore 612, 618
        }
    }
}
